// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SeniorProject
{
	public partial class SettingsController : UIViewController
	{
		public SettingsController (IntPtr handle) : base (handle)
		{
		}
	}
}
